apiVersion: v1
kind: Namespace
metadata:
  name: gitops-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubefusion-backend
  namespace: gitops-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubefusion-cluster-reader
rules:
- apiGroups: [""]
  resources: ["pods","nodes","services","events","namespaces","persistentvolumeclaims","persistentvolumes"]
  verbs: ["get","list","watch"]
- apiGroups: ["apps"]
  resources: ["deployments","statefulsets","daemonsets","replicasets"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubefusion-cluster-reader
subjects:
- kind: ServiceAccount
  name: kubefusion-backend
  namespace: gitops-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubefusion-cluster-reader
