FROM golang:1.23-alpine AS build
WORKDIR /src
COPY . .
RUN go mod tidy && go build -o /out/kubefusion-server ./cmd/server

FROM gcr.io/distroless/base-debian12
COPY --from=build /out/kubefusion-server /kubefusion-server
EXPOSE 8080
ENTRYPOINT ["/kubefusion-server"]
