apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubefusion-backend
  namespace: gitops-platform
spec:
  selector:
    matchLabels:
      app: kubefusion-backend
  endpoints:
  - port: http
    interval: 15s
